(() => {
  const catalog=window.DIO_PRODUCT_CATALOG||[];
  const email='dio_workflows@outlook.com';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const mail=p=>{const subject=`DIO CONTROLLED PILOT / ${p.name}`;const body=[`DIO CONTROLLED PILOT REQUEST`,``,`Product: ${p.name}`,`Offer: ${p.offer}`,``,`Organisation: `,`Name: `,`Reply email: `,``,`Bounded problem / case: `,``,`Material available: `,``,`I understand consequential decisions and external release remain human-authority bound.`].join('\n');return `mailto:${email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`};
  const families=['All',...new Set(catalog.map(p=>p.family))];
  if(document.body.dataset.view==='portfolio'){
    const grid=document.querySelector('#grid'),search=document.querySelector('#search'),filters=document.querySelector('#filters');let active='All';
    filters.innerHTML=families.map(f=>`<button class="filter${f==='All'?' active':''}" data-family="${esc(f)}">${esc(f)}</button>`).join('');
    const render=()=>{const q=(search.value||'').trim().toLowerCase();const rows=catalog.filter(p=>(active==='All'||p.family===active)&&(!q||[p.name,p.headline,p.buyer,p.offer,p.family].join(' ').toLowerCase().includes(q)));grid.innerHTML=rows.length?rows.map(p=>`<article class="card"><span class="badge">${esc(p.proof)}</span><div class="family">${esc(p.family)}</div><h2>${esc(p.name)}</h2><p class="headline">${esc(p.headline)}</p><p class="buyer"><b>Built for:</b> ${esc(p.buyer)}</p><div class="card-actions"><a class="button" href="${encodeURIComponent(p.slug)}/">VIEW PILOT</a><a class="button ghost" href="${mail(p)}">START</a></div></article>`).join(''):'<div class="empty">No product matches that search.</div>'};
    filters.addEventListener('click',e=>{const b=e.target.closest('[data-family]');if(!b)return;active=b.dataset.family;filters.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()});search.addEventListener('input',render);render();
  }
  if(document.body.dataset.view==='product'){
    const slug=document.body.dataset.product||new URLSearchParams(location.search).get('product');const p=catalog.find(x=>x.slug===slug);const root=document.querySelector('#product');
    if(!p){root.innerHTML='<div class="wrap producthero"><h1>Product not found.</h1><p><a class="button" href="../">Return to the 38-product portfolio</a></p></div>';return;}
    document.title=`${p.name} | DIO Controlled Pilot`;
    if(document.body.dataset.product && !document.querySelector('link[rel="canonical"]')){const c=document.createElement('link');c.rel='canonical';c.href=`https://byron2306.github.io/DIO-Workflows/products/${encodeURIComponent(p.slug)}/`;document.head.appendChild(c);}
    const li=xs=>xs.map(x=>`<li>${esc(x)}</li>`).join('');
    root.innerHTML=`<section class="producthero"><div class="wrap"><div class="breadcrumb"><a href="../">38-product portfolio</a> / ${esc(p.family)}</div><p class="eyebrow">${esc(p.family)} · CONTROLLED ROUTE PROVEN</p><h1>${esc(p.name)}</h1><p class="lead">${esc(p.headline)}</p><p><b>For:</b> ${esc(p.buyer)}</p></div></section><div class="wrap offergrid"><main><section class="panel"><p class="eyebrow">THE OFFER</p><h2 class="offer">${esc(p.offer)}</h2><p>Bring one bounded, authorised case. DIO runs the product's proof-backed controlled route, binds the resulting artifacts and evidence, and returns a human-reviewable pack. We start narrow on purpose so the first engagement produces inspectable evidence instead of a transformation programme.</p><div class="facts"><div class="fact"><small>Scope</small><b>One bounded case</b></div><div class="fact"><small>Route</small><b>Controlled route proven</b></div><div class="fact"><small>Decision</small><b>Human-owned</b></div><div class="fact"><small>Commercial step</small><b>Pilot quote after scope</b></div></div></section><section class="panel"><h2>Bring this</h2><ul>${li(p.bring)}</ul></section><section class="panel"><h2>Get this</h2><ul>${li(p.deliverables)}<li>Hash-bound DIO processing / proof receipt where applicable</li></ul></section><section class="panel"><h2>What “proven” means</h2><p>${esc(p.proof)} in DIO's 38/38 controlled-route proof campaign. The route has executed against controlled fixtures or governed upstream receipts and produced verified artifacts. A pilot still requires authorised customer material and human review.</p><div class="boundary"><b>Authority boundary.</b> ${esc(p.boundary)}</div></section></main><aside><section class="panel cta-panel"><p class="eyebrow">START SMALL. PROVE VALUE.</p><h2>Put one real case through ${esc(p.name)}.</h2><p>Send the bounded problem, what material you can authorise for review, and the outcome you need prepared. We scope the pilot before any consequential external action.</p><a class="button" href="${mail(p)}">REQUEST ${esc(p.name.toUpperCase())} PILOT ↗</a><p><small>Current intake bridge: ${email}<br>No public intake API is required to start.</small></p><p><a href="../">← Explore all 38 pilots</a></p></section></aside></div>`;
  }
})();
